stages:
  - deploy

deploy-job:
  stage: deploy
  image: python:latest
  script:
    - apt-get install -y make
    - pip install twine poetry
    - make build 
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

